version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-benefitmoa
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: benefitmoa
      MYSQL_USER: benefitmoa_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data:
